### ISSUE TITLE
Can I change nuxt dir?

### ISSUE THREAD

**Issue by yuta0801** [skyrpex/laravel-nuxt-js#12]
It is redundant to put nuxt's development directory under laravel resources, especially in projects where the front-end (nuxt) and back-end (laravel) teams are separate.

How can I change nuxt dir path? Thank you

**Comment by davidjr82** [comment]
If using nuxt v2, ya can do this in nuxt.config.js:

```
require('dotenv').config();

module.exports = {
  mode: 'spa',

  srcDir: __dirname,

  generate: {
    dir: "public/spa",
  },

  router: {
    // base: '/spa/',
  },
...
```

Hope this helps

**Comment by yuta0801** [comment]
Thank you for your help. but when I run `laravel-nuxt dev`, it has error
```[laravel] Could not open input file: artisan```

My project file tree:
```
ProjectDir
├── laravel
│   ├── app
│   └── ...
└── nuxt
    └── pages
```

**Comment by skyrpex** [comment]
I guess the problem is solved with the laravelPath option, right?
