### ISSUE TITLE
Can't get production working.

### ISSUE THREAD

**Issue by ABilenduke** [skyrpex/laravel-nuxt-js#18]
I ran laravel-nuxt build. Set up nginx as a proxy. But I will just get a 502 error. Any idea how I can get it working?

**Comment by skyrpex** [comment]
What do you exactly mean with setting up nginx as a proxy? You should serve your application as usual (handling php files and serving static assets).

**Comment by ABilenduke** [comment]
Oh my god lol I tried to follow the setup on the nuxt page for awhile... I feel like an idiot.

**Comment by skyrpex** [comment]
Don't worry! Haha Let me know if you still have any issue.
