### ISSUE TITLE
Wrong output on WSL/Ubuntu in dev mode

### ISSUE THREAD

**Issue by ow** [skyrpex/laravel-nuxt-js#19]
Hey! I followed all of your steps to the letter and am getting a weird situation where the server is up/works, but the files are in the wrong place in development: in `.nuxt` rather than `public/nuxt` - have you seen this before?

Oddly enough, switching to `yarn build` actually makes them output in the right place, but without the watch as expected....

**Comment by skyrpex** [comment]
Hi @ow :)

The `.nuxt` folder is always created by Nuxt (it's used for temporary files and so).

* If you run `npm run build` (or `yarn build`), you should end up with a directory in `public/_nuxt` containing all the production ready files. No watch mode here.
* If you run `npm run dev` (or `yarn dev`), the watch mode should be enabled (with the necessary dev servers up and running).

Isn't that the case for any of the two commands?
