### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by yodyyyy** [skyrpex/laravel-nuxt-js#20]
It's possible to add csrf meta tags inside ```<head>``` like vue does?
Thank you

**Comment by skyrpex** [comment]
You could do it in the PHP packages by modifying the https://github.com/skyrpex/laravel-nuxt/blob/c5a1ceb56ee5b4fd3ef5afdfc9bddce291715014/src/Controllers/NuxtController.php#L30 line. You could append the meta tag before the `</head>`.

Anyway, I would suggest to use cookies instead.
