### ISSUE TITLE
Update dependencies (vulnerabilities: 1 high, 2 moderate)

### ISSUE THREAD

**Issue by dfaldana** [skyrpex/laravel-nuxt-js#25]
Hello:

As `npm audit` shows (_using the latest 1.5.0 version_), there are the following vulnerabilities:

- js-yaml (Moderate: Denial of Service and **High**: Code Injection)
- webpack-bundle-analyzer (Moderate: Cross-Site Scripting)

_Thanks,_

**Comment by skyrpex** [comment]
HI @dfaldana, thanks for pointing it out.

Fixed in https://github.com/skyrpex/laravel-nuxt-js/releases/tag/v1.5.1

**Comment by skyrpex** [comment]
Seems there's more of those. Will check it as well.

**Comment by dfaldana** [comment]
Thanks :)

**Comment by skyrpex** [comment]
This should be fixed now!

**Comment by dfaldana** [comment]
Thanks!
