### ISSUE TITLE
Costumize builded folder name

### ISSUE THREAD

**Issue by webowodev** [skyrpex/laravel-nuxt-js#3]
Can i costumize the name of builded _nuxt folder in public folder ?

**Comment by skyrpex** [comment]
Yes! Use `build.publicPath` [config option](https://nuxtjs.org/api/configuration-build#publicpath).

Note that you *must* add a leading slash.

```js
const laravelNuxt = require("laravel-nuxt");

module.exports = laravelNuxt({
    build: {
        publicPath: "/my-assets",
    },
});
```

**Comment by webowodev** [comment]
Nice! Thanks dude. You are awesome! 👍
