### ISSUE TITLE
How to change layouts?

### ISSUE THREAD

**Issue by FerVillanuevas** [skyrpex/laravel-nuxt-js#4]
i want to overwrite the default layout
resources/nuxt/layouts/default.vue not work
spa/layouts/default.vue not work

help please

**Comment by skyrpex** [comment]
Hi there. The correct path should be `resources/nuxt/layouts/default.vue`. Did you try restarting the build process?

**Comment by FerVillanuevas** [comment]
Ty bro! sorry

**Comment by skyrpex** [comment]
No problem! But is it working? haha
