### ISSUE TITLE
generate mode 

### ISSUE THREAD

**Issue by AlexeyTcapaev** [skyrpex/laravel-nuxt-js#5]
Hi, I looked at the configuration and saw in the required parameters mode: "spa", it turns out in "generate" work is not provided?

**Comment by skyrpex** [comment]
To be honest, I didn't play with the generate method before. I'm not sure
if it does conflict with the SPA mode..

**Comment by skyrpex** [comment]
I'll close this for now. If you have further issues, please open the issue again.
