### ISSUE TITLE
Host IP

### ISSUE THREAD

**Issue by sn0rcha** [skyrpex/laravel-nuxt-js#8]
Hey There,

Thanks for the module!

How do I get it to listen on any IP (eg 192.168.x.x)? - I can't seem to change it from only serving on 127.0.0.1:8000 for "npm start"?

Cheers,
Ben

**Comment by skyrpex** [comment]
Hello there! 🖖 

You can use `laravel-nuxt dev --hostname=192.168.x.x`. In order to see all of the options, type `laravel-nuxt dev -h` or `laravel-nuxt build -h`.

Regards!
